############################
## CHANGE THESE
############################

baseURL: "https://w6rstaimn.github.io/test"
title: test

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
